import { NextResponse } from "next/server";
import type { Review } from "@/lib/validations";

const REVIEWS: Review[] = [
  { id: "r4", quote: "Salam ma sœur Sara, je voulais te remercier énormément pour ce gel d'aloe vera que tu m'as conseillé pour mon visage, il était très sec. Maintenant, Dieu merci, mon visage n'est plus sec du tout. Merci beaucoup, beaucoup 🤍", name: "سهام", stars: 4.5, timeAgo: "" },
  { id: "r5", quote: "Salam ma sœur Sara, j'avais pris chez toi le gel d'aloe vera pour mon visage qui était extrêmement sec. Depuis que j'utilise ce gel, ma peau est devenue hydratée, elle ne pèle plus, et le résultat est vraiment magnifique. Merci infiniment ma sœur Sara.", name: "عائشة", stars: 5, timeAgo: "" },
  { id: "r6", quote: "Salam Madame Sara, je voulais vous remercier énormément pour cette protection solaire que vous m'avez conseillée. Depuis, Dieu merci, mon visage est protégé des effets du soleil. Merci beaucoup Madame Sara.", name: "سعيدة", stars: 4, timeAgo: "" },
  { id: "r7", quote: "Protection solaire : franchement excellente, ça fait 15 jours que je l'utilise et elle donne un éclat naturel, bien meilleur qu'avec un fond de teint ou une autre formule, avec une hydratation raisonnable, pas exagérée. Elle s'applique bien sur une peau propre et sèche ; en quelques minutes elle unifie le teint sans effet brillant et donne une lumière légère.", name: "كوثر", stars: 4.5, timeAgo: "" },
  { id: "r8", quote: "Mon expérience avec le Gel Exfoliant à l'Acide Alpha Hydroxy : avant d'utiliser cet exfoliant, je luttais contre de nombreux problèmes de peau, notamment des cellules mortes que je n'arrivais pas à éliminer quoi que je fasse. Mais depuis que je l'ai intégré à ma routine, j'ai constaté une amélioration significative. Il élimine efficacement les cellules mortes, laissant mon visage magnifique et rafraîchi. J'ai maintenant un teint lisse et éclatant, et je suis ravie des résultats !", name: "Asma", stars: 5, timeAgo: "" },
  { id: "r9", quote: "Mon expérience avec le Masque Éclaircissant Nila Niacinamide : j'utilise ce masque deux fois par semaine, généralement après le gel exfoliant. Il laisse ma peau éclatante et s'est révélé très efficace pour unifier mon teint, en particulier les taches sombres autour de ma bouche. Le gel exfoliant et le masque Nila Niacinamide sont désormais des incontournables de ma routine hebdomadaire, m'aidant à garder un visage lisse et radieux.", name: "Asma", stars: 4.5, timeAgo: "" },
  { id: "r10", quote: "Mon expérience avec le Gel Natif d'Aloe Vera : je l'utilise tous les jours pour nettoyer mon visage, et c'est vraiment un produit qui change tout. Il nettoie en profondeur tout en laissant ma peau douce, nourrie et fraîche. J'adore aussi la façon dont il apaise les irritations et apporte un éclat naturel et sain à mon teint. Il fait désormais partie intégrante de ma routine de soin !", name: "Asma", stars: 5, timeAgo: "" },
  { id: "r11", quote: "Masque anti-âge à l'acide hyaluronique : je souffrais de rides au niveau du visage, surtout près des yeux. J'ai essayé de nombreuses recettes naturelles et non naturelles, mais aucune n'a été efficace. Ma fille m'a alors suggéré d'essayer le masque anti-âge d'Anissa. Au début, j'ai beaucoup hésité, mais devant son insistance, je me suis dit pourquoi ne pas essayer. Effectivement, après un mois d'utilisation (deux fois par semaine), le résultat était bon et j'ai commencé à sentir la différence : j'ai pu réduire les rides progressivement. Avec la régularité et la persévérance, le résultat était vraiment satisfaisant et magnifique. Merci aux produits Anissa Cosmetics, ils sont vraiment excellents et méritent d'être essayés.", name: "Cliente", stars: 5, timeAgo: "" },
  { id: "r12", quote: "Gel d'aloe vera : je ne peux plus m'en passer, je l'utilise quotidiennement comme nettoyant pour la peau ainsi que sous la douche. Il laisse le corps doux et le nourrit. Franchement, avant j'utilisais du savon mais j'y étais sensible, et depuis que j'ai découvert ce gel d'aloe vera, je l'ai trouvé être le meilleur choix pour moi car il nettoie la peau et le corps, et il est aussi bénéfique pour les cheveux, leur donnant une texture douce et plus d'éclat.", name: "دنيا", stars: 4, timeAgo: "" },
  { id: "r13", quote: "Le gel exfoliant: Je l'appellerai le gel miracle car c'était ma solution radicale à tous mes problèmes. Il nettoie en profondeur la peau, élimine les effets des boutons et unifie le teint. Vous verrez le résultat dès la première utilisation.", name: "Badia Oussourne", stars: 5, timeAgo: "" },
  { id: "r14", quote: "Ce que j'ai aimé avec la crème solaire, c'est qu'elle convient à tous les types de peau, en particulier à celles d'entre nous qui ont la peau délicate et sensible. Nous avons du mal à trouver une crème solaire qui nous convient. J'utilise le produit d'Anissa depuis environ 8 mois et je l'ai beaucoup aimé. Il est facile à utiliser et il donne un éclat à la peau. Je les (tous les produits de la marque anissa) recommande fortement.", name: "Badia Oussourne", stars: 4, timeAgo: "" },
  { id: "r15", quote: "Masque nila: Un très merveilleux masque. C'est une solution rapide pour assombrir la peau. Il blanchit et éclaircit la peau en seulement deux utilisations. Avant de découvrir la marque Anisa, je devais chercher du vrai Nila car on le trouve souvent frelaté, et cela peut causer des problèmes dont vous n'avez pas besoin. Avec Anisa, j'ai été soulagée de ce problème. Merci infiniment Anisa.", name: "Badia Oussourne", stars: 5, timeAgo: "" },
];

export async function GET() {
  return NextResponse.json(REVIEWS);
}
