import { NextResponse } from "next/server";
import type { Review } from "@/lib/validations";

const REVIEWS: Review[] = [
  { id: "r4", quote: "Salam ma sœur Sara, je voulais te remercier énormément pour ce gel d'aloe vera que tu m'as conseillé pour mon visage, il était très sec, surtout au niveau des joues et du menton. Maintenant, Dieu merci, mon visage n'est plus sec du tout, il ne tire plus même en fin de journée et il respire beaucoup mieux. Je l'applique après le nettoyage matin et soir depuis presque un mois, et honnêtement je ne pensais pas qu'un seul produit changerait autant les choses. Merci beaucoup, beaucoup ma sœur 🤍", name: "سهام", stars: 4.5, timeAgo: "" },
  { id: "r5", quote: "Salam ma sœur Sara, j'avais pris chez toi le gel d'aloe vera pour mon visage qui était extrêmement sec, il pelait même par endroits surtout après la douche. Depuis que j'utilise ce gel tous les soirs, ma peau est devenue hydratée, elle ne pèle plus du tout, et le résultat est vraiment magnifique, même mes proches me l'ont fait remarquer la semaine dernière. Merci infiniment ma sœur Sara, sincèrement je ne l'échangerais contre aucun autre produit maintenant.", name: "عائشة", stars: 5, timeAgo: "" },
  { id: "r6", quote: "Salam Madame Sara, je voulais vous remercier énormément pour la crème anti-imperfections que vous m'avez conseillée, j'avais des boutons un peu partout sur les joues et le menton depuis des mois. Depuis, Dieu merci, mes boutons ont beaucoup diminué, ma peau est plus calme et moins rouge qu'avant, et je n'ai plus cette sensation de peau qui tire après l'application. Je l'utilise le soir uniquement, et je vois déjà une nette différence après trois semaines. Merci beaucoup Madame Sara.", name: "سعيدة", stars: 4, timeAgo: "" },
  { id: "r7", quote: "Sérum anti-imperfections : franchement efficace, ça fait 15 jours que je l'utilise et mes boutons ont clairement diminué, sans dessécher la peau comme d'autres produits que j'avais essayés avant. Je l'applique le soir avant la crème de nuit, sur les zones où j'ai le plus de boutons, et en quelques jours le teint était déjà plus net et moins irrité. La texture est légère, elle pénètre vite et ne laisse aucune sensation collante, ce qui change vraiment de mes anciens sérums.", name: "كوثر", stars: 4.5, timeAgo: "" },
  { id: "r8", quote: "Mon expérience avec le Gel Exfoliant AHA : avant de l'utiliser, je luttais contre pas mal de problèmes de peau, surtout des cellules mortes que je n'arrivais jamais à éliminer complètement malgré plusieurs tentatives. Depuis que je l'ai intégré à ma routine deux fois par semaine, j'ai constaté une vraie amélioration, il élimine efficacement les cellules mortes et laisse mon visage frais et lisse dès la première utilisation. J'ai maintenant un teint uniforme et éclatant, et je suis vraiment ravie.", name: "Asma", stars: 5, timeAgo: "" },
  { id: "r9", quote: "Mon expérience avec le Masque Éclaircissant : je l'utilise deux fois par semaine, généralement après le gel exfoliant, en couche fine sur tout le visage. Il laisse ma peau éclatante et s'est révélé très efficace pour unifier mon teint, en particulier les taches sombres autour de ma bouche qui me complexaient depuis longtemps. Le gel exfoliant et ce masque sont désormais des incontournables de ma routine hebdomadaire, ils m'aident vraiment à garder un visage lisse et radieux toute la semaine.", name: "Asma", stars: 4.5, timeAgo: "" },
  { id: "r10", quote: "Mon expérience avec le Gel d'Aloe Vera : je l'utilise tous les jours pour nettoyer mon visage après le démaquillage, et c'est vraiment un produit qui change tout dans ma routine. Il nettoie en profondeur tout en laissant ma peau douce, nourrie et fraîche, sans jamais tirer comme certains nettoyants que j'avais avant. J'adore aussi la façon dont il apaise les irritations et apporte un éclat naturel et sain à mon teint, surtout les jours où ma peau est plus sensible que d'habitude.", name: "Asma", stars: 5, timeAgo: "" },
  { id: "r11", quote: "Masque anti-âge : je souffrais de rides au niveau du visage, surtout près des yeux, et j'avais essayé pas mal de recettes sans grand résultat. Ma fille m'a suggéré d'essayer celui d'Anissa, j'ai hésité au début mais devant son insistance je me suis dit pourquoi pas. Après un mois d'utilisation, deux fois par semaine, le résultat était bon et j'ai commencé à sentir la différence, les rides se sont réduites progressivement. Merci aux produits Anissa, ils méritent vraiment d'être essayés.", name: "Cliente", stars: 5, timeAgo: "" },
  { id: "r12", quote: "Gel d'aloe vera : je ne peux plus m'en passer, je l'utilise quotidiennement comme nettoyant pour la peau ainsi que sous la douche. Il laisse le corps doux et le nourrit. Franchement, avant j'utilisais du savon mais j'y étais sensible, et depuis que j'ai découvert ce gel d'aloe vera, je l'ai trouvé être le meilleur choix pour moi car il nettoie la peau et le corps, et il est aussi bénéfique pour les cheveux, leur donnant une texture douce et plus d'éclat.", name: "دنيا", stars: 4, timeAgo: "" },
  { id: "r13", quote: "Le gel exfoliant : je l'appellerai le gel miracle car c'était ma solution radicale à tous mes problèmes de peau grasse et de points noirs qui revenaient sans arrêt. Il nettoie en profondeur, élimine les effets des boutons et unifie le teint dès les premières applications, et surtout il ne laisse pas la peau tirée comme d'autres exfoliants que j'avais testés avant. Vous verrez le résultat dès la première utilisation, franchement je le recommande à toutes celles qui ont une peau à imperfections.", name: "Badia Oussourne", stars: 5, timeAgo: "" },
  { id: "r14", quote: "Ce que j'ai aimé avec le pack anti-âge, c'est qu'il regroupe tout ce qu'il faut sans avoir à chercher chaque produit séparément, ce qui m'a fait gagner beaucoup de temps et un peu d'argent aussi. J'utilise les produits d'Anissa depuis environ 8 mois et je les ai beaucoup aimés, ma peau est plus ferme et plus lumineuse qu'avant. C'est facile à suivre comme routine, même le soir quand je suis fatiguée, et ça donne un bel éclat à la peau. Je recommande fortement toute la gamme Anissa.", name: "Badia Oussourne", stars: 4, timeAgo: "" },
  { id: "r15", quote: "Masque nila : un très merveilleux masque, c'est une solution rapide pour unifier le teint. Il éclaircit la peau en seulement deux utilisations, ce qui m'a vraiment surprise au début. Avant de découvrir la marque Anissa, je devais chercher du vrai nila au marché car on le trouve souvent frelaté, et cela peut causer des problèmes de peau dont on n'a vraiment pas besoin. Avec Anissa, j'ai été soulagée de ce souci une fois pour toutes, je sais enfin ce que j'applique sur mon visage. Merci infiniment.", name: "Badia Oussourne", stars: 5, timeAgo: "" },
];

export async function GET() {
  return NextResponse.json(REVIEWS);
}
