import { NextResponse } from "next/server";
import type { Review } from "@/lib/validations";

const REVIEWS: Review[] = [
  { id: "r4", quote: "سلام وعليكم ختي سارة بغيت نشكرك بزاااف علا هادك جل الصبار لي نصحتيني بيه لوجهي كن جاف بزااااف دبا الحمدلله مابقش وجهي جاف كان نشكراك بزاااف بزاااف 🤍", name: "سهام", stars: 4.5, timeAgo: "" },
  { id: "r5", quote: "سلام وعليكم ختي سارة انا لي كنت خديت من عندك جل الصبار لوجهي حنت كان وجهي جاف لواحد درجة لي بزاااف من نهار درت جل الصبار ماشاءالله وليت كنحس بوجهي ولا رطب او مابقاش كي تقشر ليا او عطني نتيجة لي زوينة بزاااف كول شكر ليك اختي سارة", name: "عائشة", stars: 5, timeAgo: "" },
  { id: "r6", quote: "سلام وعليكم مدام سارة بغيت نشكرك بزاااف علا هادك واقي شمس لي نصحتيني بيها لوجهي تبعتو الوجهي الحمد لله وجهي صفا ليا من بوقع ديال شمس شكران ليك بزاأاااف مدام سارة", name: "سعيدة", stars: 4, timeAgo: "" },
  { id: "r7", quote: "واقي شمس: بصراحة رائع وافقني هادي 15 يوم نستعملو كيعطي إشراقة طبيعية احسن من فودوتان او تركيبة تانتي زائد ترطيب معقول غير مبالغ فيه. غير اتخدم مزيان على وجه نظیف و جاف غیر دقائق را کيوالم لون البشرة بدون لمعة وكيعطي إضاءة خفيفة", name: "كوثر", stars: 4.5, timeAgo: "" },
  { id: "r8", quote: "My Experience with Gel Exfoliant Alpha Hydroxy Acid: Before using this exfoliant, I struggled with numerous skin issues, particularly dead skin cells that I couldn't seem to remove no matter what I tried. However, since incorporating the Gel Exfoliant into my routine, I've noticed a significant improvement. It effectively removes dead skin cells, leaving my face beautiful and refreshed. I now have a smooth, glowing complexion, and I couldn't be happier with the results!", name: "Asma", stars: 5, timeAgo: "" },
  { id: "r9", quote: "My Experience with the Nila Niacinamide Brightening Mask: I use this mask twice a week, usually after applying the gel exfoliant. It leaves my skin glowing and has been incredibly effective in evening out my complexion, particularly the dark spots around my mouth. Both the gel exfoliant and the Nila Niacinamide Brightening Mask have now become essential parts of my weekly skincare routine, helping me maintain a smooth and radiant face.", name: "Asma", stars: 4.5, timeAgo: "" },
  { id: "r10", quote: "My Experience with Gel Natif d'Aloe Vera: I've been using Gel Natif d'Aloe Vera daily to cleanse my face, and it's truly a game-changer. It deeply cleanses while leaving my skin feeling soft, nourished, and refreshed. I also love how it soothes any irritation and adds a natural, healthy glow to my complexion. It's now an essential part of my skincare routine!", name: "Asma", stars: 5, timeAgo: "" },
  { id: "r11", quote: "ماسك ضد الشيخوخة حمض الهيالورونيك: كنت اعاني من التجاعيد على مستوى الوجه وتحديدا بجانب العنينين. جربت العديد من الوصفات الطبيعية و غير الطبيعية الا أنها لم تجد نفعا. بعدها اقترحت علي ابنتي ان استعمل ماسك انسة ضد الشيخوخة. في البداية ترددت كثيرا لكن مع الحاح ابنتي قلت لما لا اجربه. و فعلا بعد استعماله لمدة شهر (مرتين في الاسبوع) أعطى نتيجة جيدة و بدأت أشعر بالفرق استطعت ان اتخلص من التجاعيد بشكل تدريجي. مع المداومة و الاستمرار كانت النتيجة جد مرضية وارئعة. شكرا لمنتجات Anissa cosmetics انها حقا رائعة وتستحق التجربة.", name: "Cliente", stars: 5, timeAgo: "" },
  { id: "r12", quote: "جيل الصبار: ماكايفارقنيش ديما كانستعملو بشكل يومي كمنظف للبشرة و كذلك اثناء الاستحمام. كايخلي الجسم ناعم و كيغذيه. صراحة قبل كنت كانستخدم الصابونة و لكن عندي حساسية منها و ملي اكتشفت جيل الصبار لقيتو الخيار الافضل بالنسبة ليا لحقاش كينظف البشرة و الجسم و كذلك مفيد للشعر و كايعطيه ملمس ناعم و اكثر إشراقة.", name: "دنيا", stars: 4, timeAgo: "" },
  { id: "r13", quote: "Le gel exfoliant: Je l'appellerai le gel miracle car c'était ma solution radicale à tous mes problèmes. Il nettoie en profondeur la peau, élimine les effets des boutons et unifie le teint. Vous verrez le résultat dès la première utilisation.", name: "Badia Oussourne", stars: 5, timeAgo: "" },
  { id: "r14", quote: "Ce que j'ai aimé avec la crème solaire, c'est qu'elle convient à tous les types de peau, en particulier à celles d'entre nous qui ont la peau délicate et sensible. Nous avons du mal à trouver une crème solaire qui nous convient. J'utilise le produit d'Anissa depuis environ 8 mois et je l'ai beaucoup aimé. Il est facile à utiliser et il donne un éclat à la peau. Je les (tous les produits de la marque anissa) recommande fortement.", name: "Badia Oussourne", stars: 4, timeAgo: "" },
  { id: "r15", quote: "Masque nila: Un très merveilleux masque. C'est une solution rapide pour assombrir la peau. Il blanchit et éclaircit la peau en seulement deux utilisations. Avant de découvrir la marque Anisa, je devais chercher du vrai Nila car on le trouve souvent frelaté, et cela peut causer des problèmes dont vous n'avez pas besoin. Avec Anisa, j'ai été soulagée de ce problème. Merci infiniment Anisa.", name: "Badia Oussourne", stars: 5, timeAgo: "" },
];

export async function GET() {
  return NextResponse.json(REVIEWS);
}
